http://localhost:3500/api
###
http://localhost:3500/api/init_server
###
http://localhost:3500/routes
###
POST http://localhost:3500/login HTTP/1.1
content-type: application/json

{
    "email": "user1@domain.com",
    "password": "abcd1234"
}
###
http://localhost:3500/chkCode/super@bur1.com/854824
###
http://localhost:3500/validationForm
###
GET http://localhost:3500/changePassForm
###
http://localhost:3500/sendCode/user1@domain.com
###
PATCH http://localhost:3500/changePassword HTTP/1.1
content-type: application/json

{
    "email": "user1@domain.com",
    "actual": "abcd1234",
    "new": "87654321"
}
###
http://localhost:3500/api/config
###
PATCH http://localhost:3500/roles
content-type: application/json

{
    "email": "user1@domain.com",
    "roles": ["ADMIN"]
}
###
DELETE http://localhost:3500/store/sub/test.gif
###
GET http://localhost:3500/store/sub/test.gif
###
GET http://localhost:3500/img/20,10
###
GET http://localhost:3500/shell/hello.js
###
GET http://localhost:3500/db/resultado_ensayo?filter={"where":{"activo":"TP103397"}} HTTP/1.1
###
GET http://localhost:3500/User?access_token=ee2158f9401b9a52f806ae61db98dfd6b93946b53cd15b6c5ba57aab738e321230f33a01afc8d676a961fd903120672c HTTP/1.1
